[package]
name = "web-leptos"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
futures = "0.3.30"
futures-util = "0.3.30"
gloo-net = { version = "0.5.0", features = ["http"] }
js-sys = "0.3.67"
leptos = { version = "0.6.5", features = ["csr"] }
log = "0.4.20"
shared = { path = "../shared" }
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.40"
wasm-streams = "0.4.0"
