[package]
name = "counter_tauri"
version = "0.1.0"
edition = "2021"

# authors.workspace = true
# repository.workspace = true
# edition.workspace = true
# license.workspace = true
# keywords.workspace = true
# rust-version.workspace = true
[lib]
name = "tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared = { path = "../../shared" }
lazy_static = "1.4.0"
surf = "2.3.2"
futures = "0.3.30"
async-std = "1.12.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
