[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
anyhow.workspace = true
async-sse = "5.1.0"
async-std = "1.12.0"
bincode = "1.3.3"
chrono = { version = "0.4.33", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
derive_more = "0.99.17"
futures = "0.3.30"
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
uniffi = "0.26.1"
url = "2.5.0"
wasm-bindgen = "0.2.90"

[dev-dependencies]
assert_let_bind = "0.1.1"
insta = { version = "1.34.0", features = ["yaml"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }
