[package]
name = "web-yew"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures = "0.3.30"
futures-util = "0.3.30"
gloo-console = "0.3.0"
gloo-net = { version = "0.5.0", features = ["http"] }
js-sys = "0.3.67"
shared = { path = "../shared" }
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.40"
wasm-streams = "0.4.0"
yew = { version = "0.21.0", features = ["csr"] }
